# Generated by Django 5.2.1 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='films/')),
                ('trailer_url', models.URLField(blank=True)),
                ('director', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Укажите продолжительность в минутах')),
            ],
        ),
    ]
