# Generated by Django 5.2.1 on 2025-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_options_alter_film_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
